/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slidepuzzle;

import javax.sound.sampled.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author OSHINI (USJ)
 */
public class SlidePuzzle extends javax.swing.JFrame {

    //declaring class attributes
    private int[] numbers;
    private Timer timer;
    private int secondsPassed;
    private String bestPlayer;
    private int bestTime;
    private int counter;
    private boolean bool1;
    private boolean bool2;
    private boolean bool3;
    private boolean bool4;
    private static final String DATA_FILE = "slide_puzzle_data.txt";
    private Clip backgroundClip;
    private Clip clickSound;
    private Clip clickSound2;
    ArrayList state;
   
    /**
     * Creates new form SlidePuzzle
     */
    public SlidePuzzle() {
        initComponents();
        numbers = new int[16];
        loadData();
        loadAudioClips();
        playBackgroundMusic();
        state = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slide Puzzle");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(356, 356));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("1");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("2");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 153, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("3");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 153, 255));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("4");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("8");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("7");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 153, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("6");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("5");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 153, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("9");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 153, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("10");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 153, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("11");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 153, 255));
        jButton12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("12");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 153, 255));
        jButton13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(204, 153, 255));
        jButton14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("15");
        jButton14.setEnabled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(204, 153, 255));
        jButton15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("14");
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(204, 153, 255));
        jButton16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("13");
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 183, 390, 390));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        jButton18.setBackground(new java.awt.Color(204, 153, 255));
        jButton18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("Exit");
        jButton18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(204, 153, 255));
        jButton19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setText("Reset");
        jButton19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton19.setEnabled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(204, 153, 255));
        jButton20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setText("New");
        jButton20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton20.setEnabled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(204, 153, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 0, 0));
        jButton21.setText("Start");
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("  Control Panel");

        jButton22.setBackground(new java.awt.Color(204, 153, 255));
        jButton22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(0, 0, 0));
        jButton22.setText("Solution");
        jButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton22.setEnabled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 183, -1, 390));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jPanel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Best Player");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Best Time");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("     Leaderboard");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 413, -1, 160));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        jPanel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Timer");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Moves :");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("      Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 183, 190, 220));

        jPanel6.setBackground(new java.awt.Color(204, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 5));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("SLIDE PUZZLE");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Instructions");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("1. Arrange the tiles in below order. Press \"Start\" to start the game.");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("2. Press \"Reset\" to reset the board to the initial position. \"New\" is to start a new game.");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("3. Maximum time allocated for one round is 5 minutes. Maximum moves allowed are 300.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 774, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadAudioClips() {
        try {
            // Load background music
            File backgroundFile = new File("src/resources/audio/background.wav");
            AudioInputStream backgroundStream = AudioSystem.getAudioInputStream(backgroundFile);
            backgroundClip = AudioSystem.getClip();
            backgroundClip.open(backgroundStream);

            // Load click sound
            File clickFile = new File("src/resources/audio/click.wav");
            AudioInputStream clickStream = AudioSystem.getAudioInputStream(clickFile);
            clickSound = AudioSystem.getClip();
            clickSound.open(clickStream);

            // Load win sound
            File winFile = new File("src/resources/audio/win.wav");
            AudioInputStream winStream = AudioSystem.getAudioInputStream(winFile);
            clickSound2 = AudioSystem.getClip();
            clickSound2.open(winStream);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }
    }

    public void playBackgroundMusic() {
        if (backgroundClip != null) {
            backgroundClip.loop(Clip.LOOP_CONTINUOUSLY);
            backgroundClip.start();
        }
    }

    public void playClickSound() {
        if (clickSound != null) {
            clickSound.stop();
            clickSound.setFramePosition(0);
            clickSound.start();
        }
    }

    public void playWinSound() {
        if (clickSound2 != null) {
            clickSound2.stop();
            clickSound2.setFramePosition(0);
            clickSound2.start();
        }
    }

    //method to swap values of tiles if the adjacent time is empty
    public boolean CheckEmptyTile(JButton button1, JButton button2)
    {
        String shuffleNumber = button2.getText();
        
        if("".equals(shuffleNumber))
        {
            button2.setText(button1.getText());
            button1.setText("");
            return true;
        }
        else
        {
            return false;
        }       
    }
    
    //method to shuffle tile numbers when starting the game
    public void shuffleNumbers() {
    int[] winningState = {1, 2, 3, 4, 8, 7, 6, 5, 9, 10, 11, 12, 0, 15, 14, 13}; 
    int numMoves = 150; 
    int[] buttonNum;
    buttonNum = winningState.clone();

    Random random = new Random();
    for (int i = 0; i < numMoves; i++) {    
        int direction = random.nextInt(4); 
        int emptyIndex = -1;
        for (int j = 0; j < buttonNum.length; j++) {
            if (buttonNum[j] == 0) {
                emptyIndex = j;
                break;
            }
        }

        switch (direction) {
            case 0: 
                if (emptyIndex >= 4) {
                    int temp = buttonNum[emptyIndex];
                    buttonNum[emptyIndex] = buttonNum[emptyIndex - 4];
                    buttonNum[emptyIndex - 4] = temp;
                }
                break;
            case 1: 
                if (emptyIndex < 12) {
                    int temp = buttonNum[emptyIndex];
                    buttonNum[emptyIndex] = buttonNum[emptyIndex + 4];
                    buttonNum[emptyIndex + 4] = temp;
                }
                break;
            case 2: 
                if (emptyIndex % 4 != 0) {
                    int temp = buttonNum[emptyIndex];
                    buttonNum[emptyIndex] = buttonNum[emptyIndex - 1];
                    buttonNum[emptyIndex - 1] = temp;
                }
                break;
            case 3: 
                if (emptyIndex % 4 != 3) {
                    int temp = buttonNum[emptyIndex];
                    buttonNum[emptyIndex] = buttonNum[emptyIndex + 1];
                    buttonNum[emptyIndex + 1] = temp;
                }
                break;
        }
        
        // Add the current button values to the state ArrayList
        ArrayList<String> currentState = new ArrayList<>();
        for (int num : buttonNum) {
            currentState.add(String.valueOf(num));
        }
        state.add(currentState);
    }

    // Check if the final arrangement is solvable
    if (!isSolvable(buttonNum)) {
        state.clear();
        shuffleNumbers();
        return;
    }
    
    
    

    // Update the button labels based on the shuffled numbers
    for (int i = 0; i < buttonNum.length; i++) {
        int numToDisplay = buttonNum[i] == 0 ? 0 : buttonNum[i];
        numbers[i] = numToDisplay;
        switch (i) {
            case 0:
                jButton1.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 1:
                jButton2.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 2:
                jButton3.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 3:
                jButton4.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 4:
                jButton5.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 5:
                jButton6.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 6:
                jButton7.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 7:
                jButton8.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 8:
                jButton9.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 9:
                jButton10.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 10:
                jButton11.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 11:
                jButton12.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 12:
                jButton13.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 13:
                jButton14.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 14:
                jButton15.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                break;
            case 15:
                jButton16.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay)); 
                break;
        }
    }
    
    this.numbers = numbers;
}

    
    //method to check whether the generated shuffle numbers are solvable
    private boolean isSolvable(int[] puzzle) {
        int inversions = 0;
        for (int i = 0; i < puzzle.length - 1; i++) {
            for (int j = i + 1; j < puzzle.length; j++) {
                if (puzzle[i] != 0 && puzzle[j] != 0 && puzzle[i] > puzzle[j]) {
                    inversions++;
                }
            }
        }
        return inversions % 2 == 0;
    }
    
    //method to reset numbers to the initial position
    public void resetNumbers()
    {
        enableButtons();
        for (int i = 0; i < numbers.length; i++) {
            int numToDisplay = numbers[i];
            switch (i) {
                case 0:
                    jButton1.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 1:
                    jButton2.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 2:
                    jButton3.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 3:
                    jButton4.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 4:
                    jButton5.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 5:
                    jButton6.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 6:
                    jButton7.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 7:
                    jButton8.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 8:
                    jButton9.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 9:
                    jButton10.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 10:
                    jButton11.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 11:
                    jButton12.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 12:
                    jButton13.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 13:
                    jButton14.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 14:
                    jButton15.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay));
                    break;
                case 15:
                    jButton16.setText(numToDisplay == 0 ? "" : Integer.toString(numToDisplay)); 
                    break;
            }
        }
    }
    
    //methd to get the player name from the dialog box
    private String getNameFromDialog() {
        JTextField nameField = new JTextField(20);
        JPanel panel = new JPanel();
        panel.add(new JLabel("Enter your name: "));
        panel.add(nameField);

        int result = JOptionPane.showConfirmDialog(null, panel, "Welcome Player!",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            return nameField.getText();
        }
        return null;
    }
    
    //method to start the timer
    private void startTimer() {
        secondsPassed = 0;

        timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            secondsPassed++;
            if(secondsPassed > 300)
            {
                timer.stop();
                JOptionPane.showMessageDialog(SlidePuzzle.this, "Time's Up!","Slide Puzzle",JOptionPane.INFORMATION_MESSAGE);
                disableButtons();
                jButton19.setEnabled(false);
                
            }
            else
            {
                int newValue = secondsPassed;
                 int minutes = newValue / 60;
                int seconds = newValue % 60;
                jLabel2.setText(String.format("Timer  %02d:%02d", minutes, seconds));
            }
            
        }
        });
        timer.start();
    }
    
    //method to reset the timer to 00:00
    private void resetTimer() {
        if (timer != null) {
            timer.stop();
            secondsPassed = 0;
            jLabel2.setText("Timer: 00:00");
        }
    }
    
    //methld to check whether the current state of the puzzle is the winning state
   public void checkWin() {
    
    String[] currentState = new String[16];

    currentState[0] = jButton1.getText();
    currentState[1] = jButton2.getText();
    currentState[2] = jButton3.getText();
    currentState[3] = jButton4.getText();
    currentState[4] = jButton5.getText();
    currentState[5] = jButton6.getText();
    currentState[6] = jButton7.getText();
    currentState[7] = jButton8.getText();
    currentState[8] = jButton9.getText();
    currentState[9] = jButton10.getText();
    currentState[10] = jButton11.getText();
    currentState[11] = jButton12.getText();
    currentState[12] = jButton13.getText();
    currentState[13] = jButton14.getText();
    currentState[14] = jButton15.getText();
    currentState[15] = jButton16.getText();

   
    state.add(Arrays.asList(currentState));

    if (currentState[0].equals("1") && currentState[1].equals("2") && currentState[2].equals("3")
            && currentState[3].equals("4") && currentState[4].equals("8") && currentState[5].equals("7")
            && currentState[6].equals("6") && currentState[7].equals("5") && currentState[8].equals("9")
            && currentState[9].equals("10") && currentState[10].equals("11") && currentState[11].equals("12")
            && currentState[12].equals("") && currentState[13].equals("15") && currentState[14].equals("14")
            && currentState[15].equals("13")) {
        timer.stop();
        disableButtons();
        if (clickSound2 != null) {
            clickSound2.setFramePosition(0);
            clickSound2.start();
        }
        JOptionPane.showMessageDialog(SlidePuzzle.this, "Congratulations!!! You won!!!", "Slide Puzzle", JOptionPane.INFORMATION_MESSAGE);
        if (bestTime == 0) {
            bestTime = secondsPassed;
            bestPlayer = jLabel4.getText();
        } else if (bestTime > secondsPassed) {
            bestTime = secondsPassed;
            bestPlayer = jLabel4.getText();
            saveData();
        }

        jLabel8.setText(bestPlayer);
        int newValue = bestTime;

        int minutes = newValue / 60;
        int seconds = newValue % 60;

        jLabel9.setText(String.format("%02d:%02d", minutes, seconds));
    }
}

    //method to save the leaderboard data into a file
    private void saveData() {
        try (PrintWriter writer = new PrintWriter(new FileWriter(DATA_FILE))) {
            writer.println(bestTime);
            writer.println(bestPlayer);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    //method to read leaderboard data from the file
    private void loadData() {
        try (Scanner scanner = new Scanner(new File(DATA_FILE))) {
            bestTime = scanner.nextInt();
            scanner.nextLine();
            bestPlayer = scanner.nextLine();

            jLabel8.setText(bestPlayer);

            int minutes = bestTime / 60;
            int seconds = bestTime % 60;

            jLabel9.setText(String.format("%02d:%02d", minutes, seconds));
        } catch (FileNotFoundException e) {
            bestTime = 0;
            bestPlayer = "";
        }
    }

    //method to display number of movements that the tiles are moved
    public void displayMoves()
    {
         counter++;
         if(counter > 300)
         {
             timer.stop();
             JOptionPane.showMessageDialog(SlidePuzzle.this, "You have reached maximum number of moves","Slide Puzzle",JOptionPane.INFORMATION_MESSAGE);
             disableButtons();
             
         }
         jLabel7.setText(Integer.toString(counter));      
    }
    
    //enabling buttons
    public void enableButtons()
    {
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
        jButton19.setEnabled(true);
        jButton20.setEnabled(true);
        jButton22.setEnabled(true);
    }
    
    //disabling buttons
    public void disableButtons()
    {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jButton11.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
    }
    
    
    private int currentStateIndex = -1;
    
    private Timer timer2;
    private int currentIndex; 

    // Method to go back to the previous state when jButton22 is pressed
    private void goBackToPreviousState() {
        jButton19.setEnabled(false);
        jButton22.setEnabled(false);
        timer.stop();
        if (!state.isEmpty()) {
            currentIndex = currentStateIndex - 1;
            if (currentIndex < 0) {
                currentIndex = state.size() - 1; 
            }
        
        timer2 = new Timer(150, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (currentIndex >= 0) { 
                    List<String> currentState = (List<String>) state.get(currentIndex); 
                    assignStateToButtons(currentState); 
                    if (checkWinState(currentState)) {
                        ((Timer) e.getSource()).stop(); 
                        state.clear();
                        disableButtons();
                    }
                    currentIndex--; 
                } else {
                    jButton1.setText("1");
                    jButton2.setText("2");
                    jButton3.setText("3");
                    jButton4.setText("4");
                    jButton5.setText("8");
                    jButton6.setText("7");
                    jButton7.setText("6");
                    jButton8.setText("5");
                    jButton9.setText("9");
                    jButton10.setText("10");
                    jButton11.setText("11");
                    jButton12.setText("12");
                    jButton13.setText("");
                    jButton14.setText("15");
                    jButton15.setText("14");
                    jButton16.setText("13"); 
                    ((Timer) e.getSource()).stop();
                    disableButtons();
                }
            }
        });
        timer2.start();
    }
}


    private boolean checkWinState(List<String> currentState) {
         return currentState.get(0).equals("1") && currentState.get(1).equals("2") && currentState.get(2).equals("3")
            && currentState.get(3).equals("4") && currentState.get(4).equals("8") && currentState.get(5).equals("7")
            && currentState.get(6).equals("6") && currentState.get(7).equals("5") && currentState.get(8).equals("9")
            && currentState.get(9).equals("10") && currentState.get(10).equals("11") && currentState.get(11).equals("12")
            && currentState.get(12).equals("") && currentState.get(13).equals("15") && currentState.get(14).equals("14")
            && currentState.get(15).equals("13");
    }

    // Method to assign a state to the buttons
    private void assignStateToButtons(List<String> currentState) {
        jButton1.setText(currentState.get(0).equals("0") ? "" : currentState.get(0));
        jButton2.setText(currentState.get(1).equals("0") ? "" : currentState.get(1));
        jButton3.setText(currentState.get(2).equals("0") ? "" : currentState.get(2));
        jButton4.setText(currentState.get(3).equals("0") ? "" : currentState.get(3));
        jButton5.setText(currentState.get(4).equals("0") ? "" : currentState.get(4));
        jButton6.setText(currentState.get(5).equals("0") ? "" : currentState.get(5));
        jButton7.setText(currentState.get(6).equals("0") ? "" : currentState.get(6));
        jButton8.setText(currentState.get(7).equals("0") ? "" : currentState.get(7));
        jButton9.setText(currentState.get(8).equals("0") ? "" : currentState.get(8));
        jButton10.setText(currentState.get(9).equals("0") ? "" : currentState.get(9));
        jButton11.setText(currentState.get(10).equals("0") ? "" : currentState.get(10));
        jButton12.setText(currentState.get(11).equals("0") ? "" : currentState.get(11));
        jButton13.setText(currentState.get(12).equals("0") ? "" : currentState.get(12));
        jButton14.setText(currentState.get(13).equals("0") ? "" : currentState.get(13));
        jButton15.setText(currentState.get(14).equals("0") ? "" : currentState.get(14));
        jButton16.setText(currentState.get(15).equals("0") ? "" : currentState.get(15)); 
    }



    
    //----------------------------------------------Assigning button actions-----------------------------------------------------
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0); 
                    clickSound.start(); 
        }
        String temp = jButton2.getText();
        bool1 = CheckEmptyTile(jButton2, jButton1);
        bool2 = CheckEmptyTile(jButton2, jButton3);
        bool3 = CheckEmptyTile(jButton2, jButton6);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }  
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton6.getText();
        bool1 = CheckEmptyTile(jButton6, jButton2);
        bool2 = CheckEmptyTile(jButton6, jButton5);
        bool3 = CheckEmptyTile(jButton6, jButton7);
        bool4 = CheckEmptyTile(jButton6, jButton10);
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }  
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private JFrame frame;
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
       if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit", "Slide Puzzle", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }       
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton1.getText();
        bool1 = CheckEmptyTile(jButton1, jButton2);
        bool2 = CheckEmptyTile(jButton1, jButton5);
        bool3 = false;
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }  
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton3.getText();
        bool1 = CheckEmptyTile(jButton3, jButton2);
        bool2 = CheckEmptyTile(jButton3, jButton4);
        bool3 = CheckEmptyTile(jButton3, jButton7);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton4.getText();
        bool1 = CheckEmptyTile(jButton4, jButton3);
        bool2 = CheckEmptyTile(jButton4, jButton8);
        bool3 = false;
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton5.getText();
        bool1 = CheckEmptyTile(jButton5, jButton1);
        bool2 = CheckEmptyTile(jButton5, jButton6);
        bool3 = CheckEmptyTile(jButton5, jButton9);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start(); 
                }
        String temp = jButton7.getText();
        bool1 = CheckEmptyTile(jButton7, jButton3);
        bool2 = CheckEmptyTile(jButton7, jButton6);
        bool3 = CheckEmptyTile(jButton7, jButton8);
        bool4 = CheckEmptyTile(jButton7, jButton11);
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton8.getText();
        bool1 = CheckEmptyTile(jButton8, jButton4);
        bool2 = CheckEmptyTile(jButton8, jButton7);
        bool3 = CheckEmptyTile(jButton8, jButton12);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton9.getText();
        bool1 = CheckEmptyTile(jButton9, jButton5);
        bool2 = CheckEmptyTile(jButton9, jButton10);
        bool3 = CheckEmptyTile(jButton9, jButton13);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton10.getText();
        bool1 = CheckEmptyTile(jButton10, jButton6);
        bool2 = CheckEmptyTile(jButton10, jButton9);
        bool3 = CheckEmptyTile(jButton10, jButton11);
        bool4 = CheckEmptyTile(jButton10, jButton14);
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton11.getText();
        bool1 = CheckEmptyTile(jButton11, jButton7);
        bool2 = CheckEmptyTile(jButton11, jButton10);
        bool3 = CheckEmptyTile(jButton11, jButton12);
        bool4 = CheckEmptyTile(jButton11, jButton15);
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton12.getText();
        bool1 = CheckEmptyTile(jButton12, jButton8);
        bool2 = CheckEmptyTile(jButton12, jButton11);
        bool3 = CheckEmptyTile(jButton12, jButton16);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton13.getText();
        bool1 = CheckEmptyTile(jButton13, jButton9);
        bool2 = CheckEmptyTile(jButton13, jButton14);
        bool3 = false;
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton14.getText();
        bool1 = CheckEmptyTile(jButton14, jButton10);
        bool2 = CheckEmptyTile(jButton14, jButton13);
        bool3 = CheckEmptyTile(jButton14, jButton15);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0); 
                    clickSound.start();
                }
        String temp = jButton15.getText();
        bool1 = CheckEmptyTile(jButton15, jButton11);
        bool2 = CheckEmptyTile(jButton15, jButton14);
        bool3 = CheckEmptyTile(jButton15, jButton16);
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }
        checkWin();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        String temp = jButton16.getText();
        bool1 = CheckEmptyTile(jButton16, jButton12);
        bool2 = CheckEmptyTile(jButton16, jButton15);
        bool3 = false;
        bool4 = false;
        if(!temp.equals("") )                                                                                                                                         
        {
            if(bool1 == true || bool2 == true || bool3 == true || bool4 == true)
            {
                displayMoves();
                jLabel10.setText("");
            }
            else
            {
                jLabel10.setText("Cannot be moved");
            }
            
        }
        else
        {
            jLabel10.setText("Cannot be moved");
        }        
        checkWin();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start();
                }
        counter = 0;
        resetNumbers();
        jLabel7.setText(Integer.toString(counter));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if (clickSound != null) {
                    clickSound.setFramePosition(0);
                    clickSound.start(); 
                }
        counter = 0;
        frame = new JFrame("New Game");
        if(JOptionPane.showConfirmDialog(frame, "Do you want to start a new game?", "Slide Puzzle", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            enableButtons();
            shuffleNumbers();
            resetTimer();
            startTimer();
        }
        jLabel7.setText(Integer.toString(counter));
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:       
        if (clickSound != null) {
                    clickSound.setFramePosition(0); 
                    clickSound.start(); 
                }
        counter = 0;
        String name = getNameFromDialog();
                if (name != null && !name.isEmpty()) {
                    enableButtons();
                    shuffleNumbers();
                    resetTimer();
                    startTimer();
                    jLabel4.setText(name);                   
                }
        jLabel7.setText(Integer.toString(counter));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        goBackToPreviousState();
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlidePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlidePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlidePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlidePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlidePuzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
